name: Manually invalidate Akamai cache

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag used for rebuild
        required: true

jobs:
  invalidate-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Invalidate Akamai cache
        run: |
          ./invalidate.sh
