name: Manually invalidate Akamai cache

on:
  workflow_dispatch:

env:
  # OHIO_SITE_IMAGE: quay.io/operator-framework/operatorhubio
  # OHIO_REGISTRY_IMAGE: quay.io/operator-framework/upstream-community-operators
  SOURCE_BRANCH: ${{ github.ref }}

jobs:
  invalidate-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Invalidate Akamai cache
        run: |
          echo ${SOURCE_BRANCH}
          echo ${{ github.ref }}
          ./invalidate.sh
