name: Manual jobs sandbox

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning

      tags:
        description: Enviro foo
        required: false

env:
  OHIO_SITE_IMAGE: quay.io/operator-framework/operatorhubio
  OHIO_REGISTRY_IMAGE: quay.io/operator-framework/upstream-community-operators:latest
  # SOURCE_BRANCH: ${{ github.ref }}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
